export enum UserRole {
  OWNER = "OWNER",
  PRINCIPAL = "PRINCIPAL",
  ADMIN = "ADMIN",
  ADMISSIONS_OFFICER = "ADMISSIONS_OFFICER",
  ACCOUNTANT = "ACCOUNTANT",
  TEACHER = "TEACHER",
  PARENT = "PARENT",
  STUDENT = "STUDENT",
  TRANSPORT_MANAGER = "TRANSPORT_MANAGER",
}
